version: '3'
services:
  jenkins:
    container_name: jenk
    image: homejenkins
    command: bash start.sh
    ports: 
      - "8080:8080"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
    networks:
      - net

networks:
  net:
 
